"""Pydantic data models for the Stampede report pipeline."""

from datetime import date, datetime
from typing import Optional

from pydantic import BaseModel, Field


class SequenceStep(BaseModel):
    """A single step in a thermocycling sequence."""

    step_name: str  # e.g. "Hot Start", "Thermocycle", "Touchdown", "Primer mixing"
    temp_c: str  # e.g. "60", "106", "95 -> 60"
    time_s: str  # e.g. "20", "-", "30"
    cycles: str  # e.g. "2", "50", "14"
    offset: str = ""  # e.g. "-0.5", "0.1", "0.3"


class SequenceSetup(BaseModel):
    """Thermocycling sequence parameters for a run."""

    chip_type: str = ""  # e.g. "Chip Black", "Chip Black Injected"
    steps: list[SequenceStep] = Field(default_factory=list)


class ChannelAssignment(BaseModel):
    """Describes what is loaded in a specific channel."""

    channel_num: int  # 0-4
    label: str = ""  # e.g. "IS 6600 cp", "Normal reagents", "DsBio HS MSM"
    fluorophore: str = ""  # "FAM" or "ROX" (from the section it appears in)


class ReagentItem(BaseModel):
    """A single reagent in the formulation."""

    name: str
    volume_uL: float = 0.0


class ReagentFormulation(BaseModel):
    """Reagent formulation for a channel or overall."""

    channel: Optional[int] = None  # None = shared across all channels
    num_samples: Optional[int] = None
    reagents: list[ReagentItem] = Field(default_factory=list)
    total_volume_uL: float = 0.0


class CtValues(BaseModel):
    """Ct values for a single run across all channels."""

    ch0: Optional[float] = None  # None = no data ("-"), 0 = no amplification
    ch1: Optional[float] = None
    ch2: Optional[float] = None
    ch3: Optional[float] = None
    ch4: Optional[float] = None


class Run(BaseModel):
    """A single experimental run within an experiment."""

    trial_num: int
    run_id: str  # e.g. "0105_003_TS_6600_1"
    ct_fam: CtValues = Field(default_factory=CtValues)
    ct_rox: CtValues = Field(default_factory=CtValues)
    notes: str = ""
    sample_setup: str = ""  # e.g. "Injected", "liquid inject"
    batch_number: str = ""
    run_notes: str = ""
    sequence: Optional[SequenceSetup] = None
    video_file: str = ""
    report_file: str = ""


class Experiment(BaseModel):
    """A complete experiment parsed from a device testing sheet."""

    source_file: str = ""  # filename or Google Drive file ID
    experiment_date: Optional[date] = None
    purpose: str = ""
    experiments_desc: str = ""  # "Experiments:" field
    tester: str = ""
    device: str = ""  # e.g. "TS-003"
    notes: str = ""
    resume: str = ""  # conclusions/summary from the scientist
    channel_assignments: list[ChannelAssignment] = Field(default_factory=list)
    reagent_formulations: list[ReagentFormulation] = Field(default_factory=list)
    runs: list[Run] = Field(default_factory=list)


class Goal(BaseModel):
    """A team goal from the goals spreadsheet."""

    short_name: str
    requirements: str
    points: int = 0
    sign_off: str = ""
    due_date: str = ""
    goal_type: str = ""
    notes: str = ""


class JournalEntry(BaseModel):
    """A single dated journal entry."""

    entry_date: Optional[date] = None
    date_str: str = ""  # original date string
    author: str = ""
    content: str = ""
    source_file: str = ""


class WeeklyData(BaseModel):
    """All data collected for a weekly report."""

    week_start: date
    week_end: date
    experiments: list[Experiment] = Field(default_factory=list)
    journal_entries: list[JournalEntry] = Field(default_factory=list)
    goals: list[Goal] = Field(default_factory=list)


class HalfYearSummary(BaseModel):
    """Summary of a half-year period generated by the bootstrap process."""

    period: str  # e.g. "H1_2022"
    start_date: str
    end_date: str
    milestones: str = ""
    technical_evolution: str = ""
    key_findings: str = ""
    challenges: str = ""
    team_process: str = ""
    state_at_end: str = ""
    raw_summary: str = ""  # full AI-generated summary text
    experiments_processed: int = 0
    journals_processed: int = 0


class ProjectArc(BaseModel):
    """Synthesized project narrative from all half-year summaries."""

    generated_date: str = ""
    narrative: str = ""  # full AI-generated project arc text
    half_year_summaries: list[str] = Field(default_factory=list)  # period labels


class CumulativeLearnings(BaseModel):
    """Accumulated learnings from weekly runs."""

    last_updated: str = ""
    weeks_analyzed: int = 0
    key_learnings: list[str] = Field(default_factory=list)
    open_questions: list[str] = Field(default_factory=list)
    experiment_history_summary: dict = Field(default_factory=dict)
    goal_progress: dict = Field(default_factory=dict)


class AnalysisResult(BaseModel):
    """Output from Stage 1 Claude analysis."""

    experiment_families: str = ""
    executive_summary: str = ""
    experiment_analysis: str = ""
    contradictions: str = ""
    cross_experiment_insights: str = ""
    updated_learnings: Optional[CumulativeLearnings] = None
    raw_response: str = ""


class RecommendationResult(BaseModel):
    """Output from Stage 2 Claude recommendations."""

    goal_assessment: str = ""
    strategic_direction: str = ""
    recommended_experiments: str = ""
    experiments_to_avoid: str = ""
    constraints_summary: str = ""
    raw_response: str = ""
